### ISSUE TITLE
Included objects in model 

### ISSUE THREAD

**Issue by aBuder** [phillwiggins/flutter_parse_sdk#10]
Hi, is there an example available, where I have an Pointer object included in an response?

**Comment by phillwiggins** [comment]
Hey

Sorry we haven't added that feature just yet. It would be the case of doing
a double query at the moment from the pointer objects ID.

Hopefully we will get this feature in shortly.

**Comment by aBuder** [comment]
Should you need help? Hole long I have to wait for feature?

**Comment by phillwiggins** [comment]
Any help would be gratefully appreciated. Obviously with the time of year
it's going to be a bit of a break then straight back to it January.

As the SDK is very immature at the moment, please do pick something your
comfortable with and jump aboard.

**Comment by phillwiggins** [comment]
Hey, should be able to work with this now?

**Comment by ScanEat** [comment]
For me, it's actually not working but from the REST API Guide, it seems that it could be easier than doing double queries.

For example, if we have Diet_Plans objects with GameScore pointer, we can retrieve complete GameScore object with one include.

```
curl -X GET \
  -H "X-Parse-Application-Id: APPLICATION_ID" \
  -H "X-Parse-REST-API-Key: ${REST_API_KEY}" \
  -G \
  --data-urlencode 'include=["gameScore"]' \
https://parseapi.back4app.com/classes/Diet_Plans
```

**Comment by phillwiggins** [comment]
That's not the correct implementation of it...

include should be added to a query... i.e. queryBuilder.greaterThan(DietPlan.keyFat, 20);

    void query() async {
        var response = await QueryBuilder<DietPlan>(DietPlan());
        ..greaterThan(DietPlan.FAT, 20)
        ..include("gameScore")
        .query();
    }

Try something like that? I'm not sure if the syntax is correct but the include statement simple tells the api to include the full object, rather than just a pointer reference.

**Comment by ScanEat** [comment]
I tried many times and your syntax isn't correct :/

**Comment by phillwiggins** [comment]
Would this work? There was a semi colon added incorrectly. Regardless, build a query that will actually return an object that contains another object.

void query() async {
    var response = await QueryBuilder<DietPlan>(DietPlan())
    ..greaterThan(DietPlan.FAT, 20)
    ..include("gameScore")
    .query();
}

**Comment by phillwiggins** [comment]
This isn't related to the library. Please review the edited comment above. This is Dart syntax issues over library issues.

**Comment by ScanEat** [comment]
https://image.noelshack.com/fichiers/2019/03/3/1547631106-capture-d-ecran-2019-01-16-a-10-30-54.png

**Comment by phillwiggins** [comment]
Confirmed... This does look like a bug. I'll try and add a fix for 1.0.6.

Thanks for letting me know.

**Comment by phillwiggins** [comment]
Can we test this again? The code looks identical to other SDK's and should be working? I've added support for query encoding that might potentially work better...

**Comment by ScanEat** [comment]
I test but I don't know if my code (...includeObject(["gameScore"])) is correct.

```
void query() async {
    var queryBuilder = QueryBuilder(DietPlan())
      ..includeObject(["gameScore"]);

    var response = await queryBuilder.query();

    if (response.success && response.result != null) {
      print(
          "Result: ${((response.result as List<dynamic>).first as DietPlan).toString()}");
    } else {
      print("Result: ${response.error.message}");
    }
  }
```

And I have an issue :

```
[ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
NoSuchMethodError: The getter 'path' was called on null.
Receiver: null
Tried calling: path
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      new ParseFile (file:///Users/fabian/Desktop/flutter_parse_sdk-release-1.0.9/lib/src/objects/parse_file.dart:31:42)
#2      parseDecode (file:///Users/fabian/Desktop/flutter_parse_sdk-release-1.0.9/lib/src/utils/parse_decoder.dart:67:18)
#3      ParseBase.fromJson.<anonymous closure> (file:///Users/fabian/Desktop/flutter_parse_sdk-release-1.0.9/lib/src/objects/parse_base.dart:74:32)
#4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#5      ParseBase.fromJson (file:///Users/fabian/Desktop/flutter_parse_sdk-release-1.0.9/lib/src/objects/parse_base.dart:64:16)
#6      parseDecode (file:///Users/fabian/Desktop/flutter_parse_sdk-release-1.0.9/lib/src/utils/parse_decoder.dart:65:37)
#7      ParseBase.fromJson.<anonymous closure> (file:///Users/fabian/Desktop/flutter_parse_sdk-release-1.0.9/lib/src/objects/parse_base.dart:74:32)
#8      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370:8)
#9      ParseBase.fromJson (file:///Users/fabian/Desktop/flutter_parse_sdk-release-1.0.9/lib/src/objects/parse_base.dart:64:16)
#10     DietPlan.clone (package:flutter_plugin_example/diet_plan.dart:13:49)
#11     ParseResponse._handleSingleResult (file:///Users/fabian/Desktop/flutter_parse_sdk-release-1.0.9/lib/src/objects/parse_response.dart:98:49)
#12     ParseResponse._handleMultipleResults (file:///Users/fabian/Desktop/flutter_parse_sdk-release-1.0.9/lib/src/objects/parse_response.dart:89:23)
#13     ParseResponse._handleSuccess (file:///Users/fabian/Desktop/flutter_parse_sdk-release-1.0.9/lib/src/objects/parse_response.dart:76:25)
#14     ParseResponse.handleResponse (file:///Users/fabian/Desktop/flutter_parse_sdk-release-1.0.9/lib/src/objects/parse_response.dart:31:16)
#15     ParseObject.handleResponse (file:///Users/fabian/Desktop/flutter_parse_sdk-release-1.0.9/lib/src/objects/parse_object.dart:218:49)
#16     ParseObject.query (file:///Users/fabian/Desktop/flutter_parse_sdk-release-1.0.9/lib/src/objects/parse_object.dart:183:14)
<asynchronous suspension>
#17     QueryBuilder.query (file:///Users/fabian/Desktop/flutter_parse_sdk-release-1.0.9/lib/src/network/parse_query.dart:168:19)
<asynchronous suspension>
#18     _MyAppState.query (package:flutter_plugin_example/main.dart:130:39)
<asynchronous suspension>
```

**Comment by ScanEat** [comment]
I test but I doesn't work, I don't have the full object GameScore in my response

My code :

```
void query() async {
    var queryBuilder = QueryBuilder(DietPlan())
      ..includeObject(["gameScore"]);

    var response = await queryBuilder.query();

    if (response.success && response.result != null) {
      print(
          "Result: ${((response.result as List<dynamic>).first as DietPlan).toString()}");
    } else {
      print("Result: ${response.error.message}");
    }
  }
```

My console :
```
Result: {"className":"Diet_Plans","objectId":"U4FyTrkpBH","createdAt":"2019-01-11T10:40:08.121Z","updatedAt":"2019-01-18T15:02:55.869Z","Name":"Test1","Fat":666,"gameScore":"{'__type': 'Pointer', className: GameScore, objectId: ebqAUbJrKw}","image":"https://picsum.photos/52"}
```

**Comment by phillwiggins** [comment]
I have tested this and it does work. I have a Pointer object in my Parse table, with a mock object in there. A reference to another row in a different table, all works.

**Comment by ScanEat** [comment]
Mmm, can you copy/past your 2 Model classes please ? Maybe I did something wrong.

**Comment by phillwiggins** [comment]
Sent via slack

**Comment by MungaraJay** [comment]
I was using parse server sdk in my app for database.

I have three class in my Back4App Dashboard which are "_User", "Office", "Office_Members".

In Office_Members class it has following columns,

1. user_id (Pointer to _User)
2. office_id (Pointer to Office)
3. count

To fetch the data including Pointer to _User as well from Office_Members, I am using following code,

QueryBuilder<ParseObject> parseQuery = QueryBuilder<ParseObject>(ParseObject("Office_Members"))
              ..whereEqualTo("office_id", ParseResponse_OfficeObject)
              ..includeObject(["user_id "]);

ParseResponse apiResponse = await parseQuery.query();

Output :

Payload : [{"className":"Office_Members","objectId":"twpDY51PUK","createdAt":"2020-08-14T09:58:59.775Z","updatedAt":"2020-08-14T09:58:59.775Z","office_id":{"__type":"Pointer","className":"Office","objectId":"4dkfSMrwBI"},"user_id":{"__type":"Pointer","className":"_User","objectId":"Hx5xJ5ABxG"},"count":1}]

In my payload response i am not getting whole user_id pointer response. I have followed the parse sdk server documentation throughout to fire parse queries.

So can anybody help me that what i might be doing wrong?

Thanks.

**Comment by aniket453** [comment]
@MungaraJay @phillwiggins @ScanEat Did you have any luck with this issue.

I am also getting same kind of issue. I am trying to fetch the values from my "Office" class and in my office class "user_id" column is the Pointer to my User class. So i also want to include user object. I am trying following code

```
QueryBuilder<ParseObject> parseQuery =
QueryBuilder<ParseObject>(ParseObject("Language"));
parseQuery.includeObject(['user_id']);

ParseResponse parseResponse = await parseQuery.query();
```

Output i am getting is : 

[{"className":" Language ","objectId":"w3U0iHfhkh","createdAt":"2020-08-16T10:23:15.961Z","updatedAt":"2020-08-16T10:23:15.961Z","name":"Lang2199","address":"Address1521","user_id":{"__type":"Pointer","className":"_User","objectId":"zbhsxhpr9x"}}]

Update this thread if anyone finds a solution.

Thanks.

**Comment by RodrigoSMarques** [comment]
@aniket453 
Which version of the plugin are you using?
