### ISSUE TITLE
ParseUser.loginWith not alike all other methods

### ISSUE THREAD

**Issue by chrbayer** [phillwiggins/flutter_parse_sdk#105]
The newly added loginWith() method directly ParseUser object instead of ParseResponse.
We should try to keep the api consistent, what is the reason of not using _loginWith() as public interface and put the functionality of current loginWith() in application if needed?

**Comment by phillwiggins** [comment]
Hey @chrbayer 

Apologies, I don't quite understand. Do you have a code example?
