### ISSUE TITLE
How to login with email?

### ISSUE THREAD

**Issue by zakiso** [phillwiggins/flutter_parse_sdk#106]
I see that there are 2 login-related interfaces, one is login using username to log in, the other is loginWith, can loginWith log in using email? Is there an example? Thanks

**Comment by rodrigosmarques** [comment]
Hy @zakiso,
loginWith its used to link your users with services like Twitter and Facebook, enabling your users to sign up or log into your application using their existing identities.

Get authdata using Facebook Login ou Google Sign and send authdata to Parse.

Only username is needed. I usually adopt username equal to the user's email.

See this link: https://docs.parseplatform.org/rest/guide/#linking-users

**Comment by zakiso** [comment]
I got it. Thanks 👍 👍 👍 👍 👍
