### ISSUE TITLE
Sugestion: Update Sample Code with New Functions

### ISSUE THREAD

**Issue by rodrigosmarques** [phillwiggins/flutter_parse_sdk#108]
Hello, @phillwiggins.

I would like to make a suggestion:

When a contributor provides a new functionality in the lib, it would be interesting to update the sample code, demonstrating its use.

For example, we have the new functionalities of anonymous login, login using authdata, ParseFile, ParseInstallation, but this is not documented.

These features I'm updating the sample code to document.

At the time of the merge, you could check and request the upgrade. What do you think of this?

Congratulations on your initiative to develop lib and I'm really happy to collaborate with it.

**Comment by phillwiggins** [comment]
Hey Rodrigo

That's a great idea! I'll ensure any merges going forward have the correct
documentation! Thanks for the contribution to this library. It's starting
to become a really powerful library to use!

Thanks
