### ISSUE TITLE
Problem with ParseQuery and DateTime

### ISSUE THREAD

**Issue by rodrigosmarques** [phillwiggins/flutter_parse_sdk#115]
I found a problem using ParseQuery with DateTime.
When sending the DateTime to the query it is not being coded correctly.

```
  var queryBuilder = QueryBuilder<ParseObject>(ParseObject('_User'))
    ..whereGreaterThan("createdAt", DateTime.now().subtract(Duration(days: 30)))
    ..whereLessThan("createdAt", DateTime.now());
  var apiResponse = await queryBuilder.query();

```

![Captura de Tela 2019-03-12 às 11 15 41](https://user-images.githubusercontent.com/17687286/54207042-38418500-44b8-11e9-9b30-baa14325ecb3.png)

DateTime in Parse Server is Map
```
{
  "__type": "Date",
  "iso": "2011-08-21T18:02:52.249Z"
}
```

I changed the function **convertValueToCorrectType** to return map, but the **MapEntry** function returns a String with the conditions of the query

**Comment by phillwiggins** [comment]
I'll check this out tonight. 

I wrote this library due to it not being available for a project, since I started I've not been able to find time to use this library. I started last night and have found a few bugs. I'll be continuing to work from the release 1.0.16 branch, hopefully will fix that shortly.

**Comment by rodrigosmarques** [comment]
Hello,
I started an analysis and will probably have to change a lot in ParseQuery. The query parameters must be encoded as a Map, to be correctly encoded in the request in json format. You can use parseEncode to transform to the correct types and send to http using queryParameters. But for this all query possibilities, must be converted to Map and today are as string. It will be a great job, but the library will be perfect.

If I can evolve in the analysis, I keep you informed.

**Comment by phillwiggins** [comment]
If you think you can do it, then go for it.

We could possibly start with one as a test?

Is it not possible to convert the string to a map using JSON encode then
use our custom encoder to convert to Parse formats?

**Comment by rodrigosmarques** [comment]
Resolved in Pull Request #123 . Waiting for the merge

**Comment by danibjor** [comment]
Seem to work fine in 1.0.16 (should be pushed to Dart packages repo? Latest is .15). 
Tested on both custom date column and built in createdAt

```
    var queryBuilder = QueryBuilder<Store>(Store());
    queryBuilder.whereGreaterThan('openedAt', DateTime.now().add(Duration(days: -30)));
    queryBuilder.whereGreaterThan('createdAt', DateTime.now().add(Duration(hours: -2, minutes: -40)));
    queryBuilder.includeObject(['city', 'manager', 'customers']);

    var response = await queryBuilder.query();

```

**Comment by phillwiggins** [comment]
Thanks for the update. Was that tested since the last push to 1.0.16? If so
I will update tonight

**Comment by danibjor** [comment]
@phillwiggins tested 5 minutes ago on v1.0.16 branch

**Comment by phillwiggins** [comment]
Just testing this now and it seems like, greaterThan and lessThan return the same results. I'll correct and amend.

**Comment by rodrigosmarques** [comment]
@phillwiggins 

this is related to the function _checkForMultipleColumnInstances

If it is the same field they must be grouped into a single condition.

For example: where = {"runCount": {"$ gt": "1", "$ lt": "500"}, "type": "D"}

This was working. It may have broken in this latest release.

**Comment by phillwiggins** [comment]
That method was always working. There was only a small change you had added in your commit which is still there.

**Comment by rodrigosmarques** [comment]
So this is weird. 
My change was because of DateTime. DateTime is a map and the function made a replaceAll of the character "}" and this caused error in the query. My change was to make sure the function only removes the last "}".

After upgrading my fork, I will redo all the tests.

**Comment by rodrigosmarques** [comment]
Resolved in branch v.1.0.16
