### ISSUE TITLE
File downloads are empty

### ISSUE THREAD

**Issue by CodeGenie1** [phillwiggins/flutter_parse_sdk#117]
Hi Phil,
   spotted this one trying to download a bitmap image stored in parse. When you call (with await) the parse_file download method, it is returning ok and the file is created in the cache directory but it has zero bytes. I think the issue is simply that the file.writeAsBytes(response.bodyBytes) at line 68 in parse_file is not being awaited, so nothing is written to the file. You could use the writeAsBytesAsync method instead or just await.

**Comment by rodrigosmarques** [comment]
Resolved in Pull Request #123 . Wait for the merge

**Comment by phillwiggins** [comment]
Resolved on branch 1.0.16. Will be released shortly.

Thanks @rodrigosmarques for the fix.

**Comment by rodrigosmarques** [comment]
@phillwiggins 
this issue can be closed.

Resolved in the last release.
