### ISSUE TITLE
Casting current user to custom object

### ISSUE THREAD

**Issue by pastordee** [phillwiggins/flutter_parse_sdk#137]
v1.0.16
can anyone help trying to cast current user to custom user object like this 
User user = ParseUser.currentUser() as User;

but I keep getting this error type 'Future<ParseUser>' is not a subtype of type 'User' in type cast,

Please I'm new to Dart 

Thanks

**Comment by phillwiggins** [comment]
Hey

Simply add '''await'''' keyword before ''''ParseUser.currentUser()'''.

No need to use the '''as User'''

**Comment by pastordee** [comment]
Hey 

Thank you for your quick reply 
I did as you suggested but I still get the same message

flutter: type 'ParseUser' is not a subtype of type 'User'

please here is my User object 

class User extends ParseUser implements ParseCloneable {
  User() : super(keyVarUsername, keyVarPassword, keyVarEmail);
  User.clone() : this();


  /// Looks strangely hacky but due to Flutter not using reflection, we have to
  /// mimic a clone
  @override
  clone(Map map) => User.clone()..fromJson(map);


  static const String keyStatus = 'status';
  static const String keyAbout = 'about';
  static const String keyDob = 'dob';
  static const String keyOnline= 'online';
  static const String keyEmailVerified = 'emailVerified';
  static const String keyFirstName = 'firstName';
  static const String keyLastName = 'lastName';
  static const String keyFullName = 'fullName';
  static const String keyGender = 'gender';
  static const String keyLastSeen = 'lastseen';

  static const String keyOrganization = 'organization';
  static const String keyBuddies = 'buddies';
  static const String keyGroups = 'groups';
  static const String keyWarriors = 'warriors';


  String get status => get<String>(keyStatus);
  set status(String status) => set<String>(keyStatus, status);

  String get about => get<String>(keyAbout);
  set about(String about) => super.set<String>(keyAbout, about);

  DateTime get dob => get<DateTime>(keyDob);
  set dob(DateTime dob) => set<DateTime>(keyDob, dob);

  bool get online => get<bool>(keyOnline);
  set online(bool online) => set<bool>(keyOnline, online);

  bool get emailVerified => get<bool>(keyEmailVerified);
  set emailVerified(bool emailVerified) => set<bool>(keyEmailVerified, emailVerified);

  String get firstName => get<String>(keyFirstName);
  set firstName(String firstName) => set<String>(keyFirstName, firstName);

  String get lastName => get<String>(keyLastName);
  set lastName(String lastName) => set<String>(keyLastName, lastName);

  String get fullName => get<String>(keyFullName);
  set fullName(String fullName) => super.set<String>(keyFullName, fullName);

  String get gender => get<String>(keyGender);
  set gender(String gender) => set<String>(keyGender, gender);

  DateTime get lastseen => get<DateTime>(keyLastSeen);
  set lastseen(DateTime lastseen) => set<DateTime>(keyLastSeen, lastseen);

  List<String> get organization => get<List<String>>(keyOrganization);
  set organization(List<String> organization) => set<List<String>>(keyOrganization, organization);
  List<String> get buddies => get<List<String>>(keyBuddies);
  set buddies(List<String> buddies) => set<List<String>>(keyBuddies, buddies);
  List<String> get groups => get<List<String>>(keyGroups);
  set groups(List<String> groups) => set<List<String>>(keyGroups, groups);
  List<String> get warriors => get<List<String>>(keyWarriors);
  set warriors(List<String> warriors) => set<List<String>>(keyWarriors, warriors);


}

**Comment by phillwiggins** [comment]
That's strange. That's pretty much the same as my project, show me an
example of where you use Parse user, i.e. how are you creating the user,
how are you calling it etc

**Comment by phillwiggins** [comment]
Any luck on this one?

**Comment by pastordee** [comment]
> Any luck on this one?

sorry no joy here,

var userCurr = await ParseUser.currentUser();

    var queryBuilder = QueryBuilder<User>(User())
      ..whereEqualTo("objectId", userCurr.objectId)
      ..includeObject(["creator"]);

    final userRe = await queryBuilder.query();
    if (userRe.success){
      for (var testObject in userRe.result) {
        globals.user = testObject;
      }
    }

this is the work around I'm using for now
using the current user id to query the database and save it to a global user or singleton

**Comment by pastordee** [comment]
User user = _widget.prayers[position].user; not working

User user = _widget.prayers[position].user as ParseUser; not working as well 

I still get this: 'ParseUser' is not a subtype of type 'User'

**Comment by phillwiggins** [comment]
Does your setup have the user field as a String or a pointer?

**Comment by pastordee** [comment]
I believe is a string

David Frimpong 
Prayer Circle ⭕️ allows you to pray for people leave your prayer request,  is also a prayer journal, you can create a group for you and your family, the saying is those who pray together stay together check it out
Play Store 
https://play.google.com/store/apps/details?id=co.uk.frimpong.prayercircle

App Store 
https://itunes.apple.com/us/app/prayer-circle/id1206157155?ls=1&mt=8

**Comment by phillwiggins** [comment]
Okay, it's not ideal but there is a fix on the latest branch release/1.0.17.

 `final User currentUser = await ParseUser.currentUser(customUserObject: User.clone());`

Dart is struggling to recognize the saved custom object so you need to pass an instance of the customer object to the SDK.

**Comment by pastordee** [comment]
Thanks will try it, please also i can’t get the array from the server

**Comment by gilbriatore** [comment]
Thanks, @phillwiggins, this works for me:

`final User currentUser = await ParseUser.currentUser(customUserObject: User.clone());`



> Okay, it's not ideal but there is a fix on the latest branch release/1.0.17.
> 
> `final User currentUser = await ParseUser.currentUser(customUserObject: User.clone());`
> 
> Dart is struggling to recognize the saved custom object so you need to pass an instance of the customer object to the SDK.

**Comment by gilbriatore** [comment]
> > Thanks, @phillwiggins, this works for me:
> > `final User currentUser = await ParseUser.currentUser(customUserObject: User.clone());`
> > > Okay, it's not ideal but there is a fix on the latest branch release/1.0.17.
> > > `final User currentUser = await ParseUser.currentUser(customUserObject: User.clone());`
> > > Dart is struggling to recognize the saved custom object so you need to pass an instance of the customer object to the SDK.
> 
> This strategy can be evolved to:
> 
> `final User currentUser = await User.currentUser();`
> 
> by including this static method inside the User class:
> 
> ` static Future<dynamic> currentUser() async {` ` final String? userJson = await ParseCoreData().getStore().getString(keyParseStoreUser);` ` if (userJson != null) {` ` final Map<String, dynamic> userMap = json.decode(userJson);` ` return User.clone().clone(userMap);` ` }` ` return null;` `}`

And finally, to get it updated from the server, just include this static method in the User class:

`static Future<User> getUpdatedFromServer(String? token) async {`
    `return User.clone().clone(`
       ` ((await ParseUser(null, null, null, sessionToken: token)`
          `.getUpdatedUser()).result).toJson());`
`}`

and call like this:

`final User currentUser = await User.getUpdatedFromServer(currentUser.sessionToken);`
