### ISSUE TITLE
QueryBuilder with a ParseObject encode to json not correct.

### ISSUE THREAD

**Issue by zakiso** [phillwiggins/flutter_parse_sdk#138]
When I use queryBuilder build a query and query condition contains a ParseObject then the server response a error. The error is `Unexpected token _ in JSON at position`.

This is my code:
```
///build a query
var queryBuilder = QueryBuilder<ParseObject>(ParseObject("Note"));
var book = ParseObject("Book");
....
///other query limit
....
queryBuilder.whereEqualTo(
            "book",book);
```

My console out put:  
```
....
....
where={"updatedAt":{ "$gt":{"__type":"Date","iso":"2019-03-23T16:00:00.000Z"}, "$lt":{"__type":"Date","iso":"2019-03-24T15:59:59.000Z"}},"book": {__type: Pointer, className: Books, objectId: HZ09pN5NXI}}&skip=0
```

**Comment by phillwiggins** [comment]
I don't quite understand the question, but I can see an error in your query
to begin with. Where you call:-

queryBuilder.whereEqualTo(
            "book", ParseObject);


Try this instead :-

queryBuilder.whereEqualTo(

            "book", ParseObject("Note"));n Sun, Mar 24, 2019, 09:32
炸鸡叔 <notifications@github.com> wrote:

I use queryBuilder build a query with ParseObject but get error Unexpected

**Comment by zakiso** [comment]
Sorry for my poor english.
When my query condition contains a parseObject object, the server cannot parse the data correctly.
The Book object should be wrapped in quotes.

**Comment by phillwiggins** [comment]
Oh right, so none of the elements in the books JSON object are wrapped in quotation marks?

**Comment by zakiso** [comment]
Yes

**Comment by phillwiggins** [comment]
Very strange.

What's happens if you create an instance of a Note object and call .toPointer in the whereEqualTo call?

**Comment by zakiso** [comment]
Oh strange.
Everything works fine when I manually call toPointer.This my console output:  
```
where={"updatedAt":{ "$gt":{"__type":"Date","iso":"2019-03-23T16:00:00.000Z"}, "$lt":{"__type":"Date","iso":"2019-03-24T15:59:59.000Z"}},"book": {"__type":"Pointer","className":"Books","objectId":"HZ09pN5NXI"}}&skip=0
```

my code:
```
...
queryBuilder.whereEqualTo(
            "book",book.toPointer());
...
```

**Comment by phillwiggins** [comment]
I'll look into that.

It probably should be the same output but it looks to be slightly different.

**Comment by zakiso** [comment]
But when I manually call toPointer, the parse server will not response an error.

**Comment by rodrigosmarques** [comment]
@zakiso 
Which version are you using? Show your pubscpec.yaml.

The problem with pointers has been resolved.

The correct it use Object.toPointer()

**Comment by zakiso** [comment]
@rodrigosmarques 
Everything works fine when I use this method that your provided. 
`queryBuilder.whereEqualTo("field", Object.toPointer());`

**Comment by rodrigosmarques** [comment]
@phillwiggins
Close this issue to keep open only what is in trouble.
Resolved according to the above comment
