### ISSUE TITLE
listen function like firebase

### ISSUE THREAD

**Issue by ccfiel** [phillwiggins/flutter_parse_sdk#144]
is there a listen function in flutter_parse like firebase so that every time there is new data stream in an object it will automatically updated to flutter app?

```
@override
  void initState() {
    super.initState();
    final FirebaseDatabase database = FirebaseDatabase.instance; 
    deviceRef = database.reference().child('device');
    deviceRef.onChildAdded.listen(_onEntryAdded);
  }

  _onEntryAdded(Event event) {
    setState(() {
      devices.add(Device.fromSnapshot(event.snapshot));
    });
  }
```

**Comment by rodrigosmarques** [comment]
Hi @ccfiel 
The name of this functionality in Parse is called LiveQueries.

This functionality is implemented in lib, but I do not know if there is a document example.

**Comment by ccfiel** [comment]
@rodrigosmarques 
Thanks. I found it here https://github.com/phillwiggins/flutter_parse_sdk/blob/master/lib/src/network/parse_live_query.dart

I tried to look at the doc and example app there are no live query exist :(

**Comment by rodrigosmarques** [comment]
@ccfiel 
I'll try to put together a sample code and put it here.

**Comment by ccfiel** [comment]
@rodrigosmarques 
Thanks! that would be great! :)

> @ccfiel
> I'll try to put together a sample code and put it here.

**Comment by rodrigosmarques** [comment]
@ccfiel 
I have seen a comment in the code, stating that it is still in development.

Can you confirm @phillwiggins ?

**Comment by ccfiel** [comment]
@rodrigosmarques ,

Yes I seen that also. So it means it cannot be used for now?

**Comment by rodrigosmarques** [comment]
@ccfiel 
version 1.0.17 when released, will be running Live Queries.

You can view a preview of the updated documentation here
https://github.com/phillwiggins/flutter_parse_sdk/tree/release/1.0.17, section Live Queries

**Comment by ccfiel** [comment]
@rodrigosmarques  thanks for this!
