### ISSUE TITLE
After log out the current user is not null

### ISSUE THREAD

**Issue by pcegarra** [phillwiggins/flutter_parse_sdk#145]
Im doing user.logOut(), and then Im checking if the `currentUser!=null` but it is retuning not null.
Here is the current user after log out:

![Screenshot 2019-04-05 at 13 02 51](https://user-images.githubusercontent.com/10808022/55623388-23989a00-57a3-11e9-8015-b1d2c056671e.png)

**Comment by Atteprojects** [comment]
I usually check for objectId if `currentUser != null `

**Comment by phillwiggins** [comment]
Hey, is this still an issue? 

I can look into this tonight before creating a new release.

**Comment by pcegarra** [comment]
Yes we can check for the objectId, but in the other sdks we just need to check for currentUser!=null

**Comment by phillwiggins** [comment]
Hey,

I'll look into this tonight. I'd prefer not to have a current user if there is no objectId. I potentially might make a method as well called something like, isUserAvailable that returns a bool or something.

**Comment by phillwiggins** [comment]
Fixed in the latest release
