### ISSUE TITLE
Impossible to check if email was verified

### ISSUE THREAD

**Issue by thierry-tct** [phillwiggins/flutter_parse_sdk#159]
The field `emailVerified` present in the User object returned by [Parse Server](https://docs.parseplatform.org/js/guide/#verifying-emails) is never existing here in the ParseUser class.

How can we check that the email is verified?

**Comment by rodrigosmarques** [comment]
Hi @thierry-tct 

Try this:
```dart
  final currentUser = await ParseUser.currentUser() as ParseUser;
  print('EmailVerified: ${currentUser.get("emailVerified")}');
```

Value can be null, careful when making validations

**Comment by thierry-tct** [comment]
@rodrigosmarques Thanks much. That works perfectly.

**Comment by rodrigosmarques** [comment]
@thierry-tct 
Version 20 released today has a new method for verifying:
```dart
  final currentUser = await ParseUser.currentUser() as ParseUser;
  print('EmailVerified: ${currentUser.emailVerified}');
```
