### ISSUE TITLE
Clients aren't allowed to manually update email verification

### ISSUE THREAD

**Issue by pcegarra** [phillwiggins/flutter_parse_sdk#174]
Im getting the following error updating  the current user.

```
ParseException (Type: OperationForbidden) :
Code: 119
Message: Clients aren't allowed to manually update email verification
```

This is my code:

```
  Future<bool> setUserNotifyLocations(List<String> ids) async {
    ParseUser user = await ParseUser.currentUser();
    user.set('centros', ids);
    ParseResponse response = await user.save();
    return response.success;
  }
```

Any idea? Im using the version 1.0.21

**Comment by phillwiggins** [comment]
Hey @pcegarra 

I'm not going to lie, I have 0 idea about this. This looks to be ParseServer related. I'm not certain but maybe this isn't something the SDK is suppose to do. The reason code looks like it shouldn't be possible via the SDK. What is 'centros'? It looks like it's trying to override the verification object on Parse?

**Comment by pcegarra** [comment]
I was getting the same error changing the value 'centros' or 'hamburguers' XD, my "solution" is to create a new parse user and set the object id of the current user, then save.
