### ISSUE TITLE
an example for saving image with ParseFile

### ISSUE THREAD

**Issue by alparslantopbas** [phillwiggins/flutter_parse_sdk#175]
could you please, can you give a basic working example an image save/upload with ParseFile to Parse Server?

**Comment by rodrigosmarques** [comment]
Hi @alparslantopbas,
you have to have a File. In this example, I downloaded an internet file, saved it to Local Storage, and am loading it into Parse

```dart
  var file = await _downloadFile(
      "https://i2.wp.com/blog.openshift.com/wp-content/uploads/parse-server-logo-1.png",
      "image.png");
  print("saveFile");
  ParseFile parseFile = ParseFile(file, name: "image.png", debug: true);
  var fileResponse = await parseFile.save();
  if (fileResponse.success) {
    parseFile = fileResponse.result as ParseFile;
    print(parseFile.toString());
    print("Upload with success");
  } else {
    print("Upload with failed");
  }
```

**Comment by alparslantopbas** [comment]
Thanks for the quick response, but I think this code is for file download. How can I upload a file to ParseServer ?
This is my code, but it doesn't work:
ParseFile imageOnYuz = ParseFile(_imageFileOnYuz, debug: true);

imageOnYuz.name = randomAlphaNumeric(10) + '.png';
imageOnYuz.url = '$APIURL/files/$APPKEY/${imageOnYuz.name}';
imageOnYuz.file = _imageFileOnYuz;
imageOnYuz.className = tblImages;

ParseObject images = new ParseObject(tblImages);
images.set('ImageName', imageOnYuz);
images.set('OnArkaYuz', 'OY');

var imagesResponse = await images.save();
if (imagesResponse.success) {
    print('Upload with success');
} else {
    print('Something went wrong');
}

**Comment by rodrigosmarques** [comment]
Hi @alparslantopbas ,

This code is not for download from the archive. The file download was just to create a file in the local store.

The file can be an image selected through the image_picker plugin.

The ParseFile constructor needs the File and the file name. The Debug parameter is optional.

After saving ParseFile you can save it to a ParseObject.

See the example below

```dart
  File image = await ImagePicker.pickImage(source: ImageSource.gallery);
  ParseFile parseFile = ParseFile(image, name: "image.jpg", debug: true);
  var fileResponse = await parseFile.save();
  if (fileResponse.success) {
    parseFile = fileResponse.result as ParseFile;
    print(parseFile.toString());
    print("Upload with success");
  } else {
    print("Upload with failed");
  }

  var parseObject = ParseObject("TestObjectFile", debug: true);
  parseObject.set<ParseFile>("fileImage", parseFile);
  var apiResponse = await parseObject.save();

  if (apiResponse.success) {
    print('ok');
  } else {
    print("Error: " + apiResponse.error.toString());
  }
```

**Comment by alparslantopbas** [comment]
Hi @rodrigosmarques ,

Thank you very much, it works 👍 
I finally get it and fix my code as you wrote :-)
