### ISSUE TITLE
How can I write this kind of query?

### ISSUE THREAD

**Issue by alparslantopbas** [phillwiggins/flutter_parse_sdk#176]
Hi,
How can I write this kind of query? I think named is "relational query".
For example, there are two tables: **tblOrders and tblProducts**

Like these:
**tblOrders**
objectId
productId (Pointer<tblProducts>)
Date
Quantity

**tblProducts**
objectId
ProductName

I want to this kind of result:
tblOrders.objectId   tblOrders.productId   **tblProducts.ProductName**   tblOrders.Date   tblOrders.Quantity

So, 
var apiResponse = await ParseObject('tblOrders').getAll();

but, how can I add "**ProductName**" into query?
Like T-SQL View structure?

**Comment by rodrigosmarques** [comment]
Hi @alparslantopbas 
See this example.
Maybe I made a mistake, because I typed without testing, based on a code I have.

```dart
QueryBuilder queryBuilder = QueryBuilder<ParseObject>(ParseObject('tblOrders'));
queryBuilder.includeObject(['productId']);
ParseResponse parseResponse = await queryBuilder.query();

if (parseResponse.success && parseResponse.results != null) {
  final ParseObject tblOrders = parseResponse.results[0] aa ParseObject;
  final ParseObject tblProducts = tblOrders.get<ParseObject>('productId');
  print(tblOrders.get<String>('objectId'));
  print(tblOrders.get<String>('Quantity'));
  print(tblProducts<String>('objectId'));
  print(tblProducts<String>('ProductName'));
}
```

**Comment by alparslantopbas** [comment]
Hi @**rodrigosmarques**,
Thank you very much, yes it works.
But it works only for one record (one row) (parseResponse.results[0]).
How can I all of the records?

This doesn't work:
final List<ParseObject> tblOrders = parseResponse.results[0] as List<ParseObject>;
final List<ParseObject> tblProducts = tblOrders.get<ParseObject>('productId');

**Comment by rodrigosmarques** [comment]
Hi @alparslantopbas 
Hello, I did with the first just as an example.
Make a loop in the parseResponse.results items.
For each list item retrieve tblProducts

**Comment by alparslantopbas** [comment]
Hi **@rodrigosmarques**,
Yes, it is possible to do that way. I did.
Thank you very much for your help.
