### ISSUE TITLE
1.0.22 not available why?

### ISSUE THREAD

**Issue by ccfiel** [phillwiggins/flutter_parse_sdk#201]
Hello,
When I try to install the package. error occurred

parse_server_sdk ^1.0.22 which doesn't match any versions, version solving failed.

Any idea. Why?

**Comment by zenz** [comment]
you can try it in this way:

dev_dependencies:
  # parse_server_sdk: ^1.0.21
  parse_server_sdk:
    git:
      url: git@github.com:phillwiggins/flutter_parse_sdk.git
      ref: 130121e2ff66db930739b93dcce31b577061ae0a

**Comment by rodrigosmarques** [comment]
@ccfiel 
Do not use version 22. It is not OK. Use release 21.

**Comment by phillwiggins** [comment]
Apologies, v1.0.22 is not ready yet. However, it was merged with master before it was nearly released. Hence the reason the documentation references v1.0.22.

This will be released shortly, but only once we are all happy that it's a solid release. For now use v1.0.21

**Comment by ccfiel** [comment]
thanks guys!
