### ISSUE TITLE
Following tutorial, user login throws null exeption

### ISSUE THREAD

**Issue by ctalladen78** [phillwiggins/flutter_parse_sdk#21]
Dart Error: Unhandled exception:
Failed assertion: boolean expression must not be null
#0      ParseUser._handleResponse
(file:///Users/cytaladen/.pub-cache/hosted/pub.dartlang.org/parse_server_sdk-1.0.2/lib/src/objects/parse_user.dart:185:22)
#1      ParseUser.signUp (file:///Users/cytaladen/.pub-cache/hosted/pub.dartlang.org/parse_server_sdk-1.0.2/lib/src/objects/parse_user.dart:79:5)
<asynchronous suspension>
#2      ParseService.createUser (package:flutter_ui_experiments/parse_service.dart:40:39)
<asynchronous suspension>

**Comment by phillwiggins** [comment]
Still not working?
