### ISSUE TITLE
includeObject doesn't work

### ISSUE THREAD

**Issue by cantaspinar** [phillwiggins/flutter_parse_sdk#211]
I have the following query:

`  var queryBuilder = QueryBuilder<ParseObject>(ParseObject('Robot'))
  ..includeObject(["location"]);`

However, it doesn't include the object from Location class. When I enable debug mode I get the following url:

https://parseapi.back4app.com/classes/Robot?where={}&include=location

It includes the pointer when I make a get request with a REST client. However the result I get from the plugin is different and doesn't include the pointer.

**Comment by rodrigosmarques** [comment]
Hi @cantaspinar 
Which version? 
I'm using it in version 1.0.21 with no problems.
```dart
xxxx\classes/Ad?where={"state": "ES"}&limit=1000&include=category,owner&order=createdAt
```

```dart
..."category":{"__type":"Pointer","className":"Categories","objectId":"6XyD5UhBRm"},"owner":{"__type":"Pointer", ...
```

**Comment by cantaspinar** [comment]
Hi @rodrigosmarques
I am using version 1.0.21 as well.
I can’t see the data in ur output too. Can you access fields?

**Comment by rodrigosmarques** [comment]
Hi.
I do the following:

```dart
    final user = object.get<ParseUser>('owner');

    final category = object.get<ParseObject>('category');
```

**Comment by cantaspinar** [comment]
I will try it, I assumed it hasn’t fetched the data since I can’t see the data in payload.

**Comment by rodrigosmarques** [comment]
Do you have a pointer or a relationship?

**Comment by cantaspinar** [comment]
It is a pointer

**Comment by cantaspinar** [comment]
> Hi.
> I do the following:
> 
> ```dart
>     final user = object.get<ParseUser>('owner');
> 
>     final category = object.get<ParseObject>('category');
> ```

Yeah, this works. What I was doing was converting each result to string and than map it to my own model. But it appears like you can't get full object string with pointers included without calling get method on parent object.

**Comment by srkraut** [comment]
Hello , i am having a simple problem , i have list of post with author pointer user , in list view i want to show author name from that user pointer but cant access the name , any idea ?
