### ISSUE TITLE
LiveQuery needs refactoring

### ISSUE THREAD

**Issue by rostopira** [phillwiggins/flutter_parse_sdk#217]
Current implementation spawns new separate websocket connection for every subscription
This is huge overkill and will likely cause additional load on server

**Comment by arvanus** [comment]
@rostopira are LiveQuery working for you?
See #198

**Comment by rostopira** [comment]
Yes, it works, because I'm using release branch, read last comment on issue
It also works on Flutter Web

**Comment by phillwiggins** [comment]
Hey @rostopira 

Can you look at the Web Live Query stuff you wrote. It seems to be listing invalid libraries and has dragged our Flutter library score on Pub Dev to a really low level. It looks as though something is missing? It ideally needs a hotfix pretty promptly.

**Comment by rostopira** [comment]
The only thing that it uses is `dart:html`, and it's valid library. But Dart Analyzer doesn't think so, see: https://github.com/flutter/flutter/issues/35588

**Comment by rostopira** [comment]
Actually, using `import 'dart:html' as HTML;` make dart analyzer scream on this line only, so I will provide PR with that

**Comment by rostopira** [comment]
@phillwiggins PR is ready to merge

**Comment by phillwiggins** [comment]
Greatly appreciated!
