### ISSUE TITLE
getAllItems() & query()

### ISSUE THREAD

**Issue by ScanEat** [phillwiggins/flutter_parse_sdk#23]
Hello,

I copy/paste the entire project, then I just set my 4 application constants and create a Diet_Plans table with 2 objects with the name "Test1" and "Test2.

When I call getAllItems()
`void getAllItems() async {
    var response = await DietPlan().getAll();

    if (response.success) {
      for (var plan in response.result) {
        print(ApplicationConstants.APP_NAME + ": " + (plan as DietPlan).name);
      }
    } else {
      print(ApplicationConstants.APP_NAME + ": " + response.error.message);
    }
  }`

In my terminal, there is :
`I/flutter ( 4409): Hello Flutter: Test2
I/flutter ( 4409): Hello Flutter: Test2`

The problem is that getAllItems returns 2 objects but two times the last.
(it's the same with query())

In advance, thank you for your help.

**Comment by phillwiggins** [comment]
Hi,

I've just noticed this now. Was in the latest release, there was some work done around handling responses. Will fix ASAP and let you know.

**Comment by phillwiggins** [comment]
All fixed. Objects now need to implement ParseCloneable
