### ISSUE TITLE
Does not work with flutter 1.7

### ISSUE THREAD

**Issue by gorillatapstudio** [phillwiggins/flutter_parse_sdk#238]
I verified a couple of time. Everything works for flutter 1.5 but in 1.7 i keep getting the "boolean expression must not be null" whenever make a parse server request. if i switch back to flutter 1.5, it works. I tried both the 1.0.21 an 1.0.22 versions.

**Comment by rodrigosmarques** [comment]
I am using in version 1.7. Flutter and lib version 1.0.21 and 1.0.23 with no problem.
How are you starting Parse in code?
An await is required.
See the sample code.

https://github.com/phillwiggins/flutter_parse_sdk/blob/master/example/lib/main.dart

**Comment by gorillatapstudio** [comment]
you are right. i didn't await for parse init. Thanks a million!!
