### ISSUE TITLE
Create and update object

### ISSUE THREAD

**Issue by ScanEat** [phillwiggins/flutter_parse_sdk#25]
Hello,

I think it's not an issue but I try to create and update a Diet_Plans but I didn't succeed.

Is it possible to update the documentation/tutorial to make a CRUD for Diet_Plans ?

Because, when I try this code from the README :
`var dietPlan = ParseObject('DietPlan')
	..setValue('Name', 'Ketogenic')
	..setValue('Fat', 65);`
My IDE tell me: The method 'setValue' isn't defined for the class 'ParseObject'.

In advance, thank you.

**Comment by phillwiggins** [comment]
All fixed, should be just ..set(KEY, VALUE);

In V1.0.4 we have added generics so that we can control the types we are working with. It will look something like get<String>(KEY, VALUE);

Thanks for pointing that out.
