### ISSUE TITLE
QueryBuilder does not work as expected

### ISSUE THREAD

**Issue by Vildnex** [phillwiggins/flutter_parse_sdk#258]
I'm not sure if this is an actual issue or I'm just doing something wrong but...

I'm trying to create a query something like this:

```
QueryBuilder<ParseObject>(ParseObject("Session"))
      ..whereEqualTo('user', userID)
      ..query().then((result){
        // DOING SOMETHING WITH THE RESULT
});
```
Because I want to obtain the last session of a user, or in other words to check if it's already logged-in or not.

Now the problem with that query is that every time my "result" is going to be empty, even those I have that userID in my database.

Can you help me to find out what I'm doing wrong or this is an actual issue?

**Comment by danibjor** [comment]
Session collection is not readable. Same behavior from NodeJS SDK.

**Comment by Vildnex** [comment]
if it's so, then how can I check whether the user is already logged-in or not?

**Comment by danibjor** [comment]
var user = ParseUser.currentUser();
if (user != null) {
  // Got user from local storage on device.
  // User is logged in - do stuff

}

**Comment by Vildnex** [comment]
oh, that's actually working. Sorry for this stupid question, thanks :D
