### ISSUE TITLE
[Error when object update] schema mismatch for Diet_Plans.createdAt; expected Date but got String

### ISSUE THREAD

**Issue by ScanEat** [phillwiggins/flutter_parse_sdk#27]
Hi,

There is a problem with the object update, this is my code :
`updateDietPlan() async {
    var response = await DietPlan().getObject('U4FyTrkpBH');

    if (response.success) {
      var dietPlan = (response.result as DietPlan);
      print("(before update) dietPlan: $dietPlan");

      dietPlan.set<int>('Fat', 666);
      print("(after update) dietPlan: $dietPlan");
      dietPlan.save();
    } else {
      print(ApplicationConstants.APP_NAME + ": " + response.error.message);
    }
  }`

And this is the console:
`I/flutter (17474):  
I/flutter (17474): ----
I/flutter (17474): Hello Flutter API Response (Diet_Plans : ParseApiRQ.get) :
I/flutter (17474): Status Code: 200
I/flutter (17474): Payload: {"objectId":"U4FyTrkpBH","Name":"Test1","createdAt":"2019-01-11T10:40:08.121Z","updatedAt":"2019-01-11T10:40:52.692Z","Fat":11}
I/flutter (17474): ----
I/flutter (17474): (before update) dietPlan: {"objectId":"U4FyTrkpBH","Name":"Test1","createdAt":"2019-01-11T10:40:08.121Z","updatedAt":"2019-01-11T10:40:52.692Z","Fat":11}
I/flutter (17474): (after update) dietPlan: {"objectId":"U4FyTrkpBH","Name":"Test1","createdAt":"2019-01-11T10:40:08.121Z","updatedAt":"2019-01-11T10:40:52.692Z","Fat":666}
I/flutter (17474):  
I/flutter (17474): ----
I/flutter (17474): Hello Flutter API Response (Diet_Plans : ParseApiRQ.save) :
I/flutter (17474): Status Code: 111
I/flutter (17474): Type: IncorrectType
I/flutter (17474): Error: schema mismatch for Diet_Plans.createdAt; expected Date but got String
I/flutter (17474): ----
`

In advance, thank you.

**Comment by phillwiggins** [comment]
Thank you, will look at that now and release in v1.0.5.

**Comment by phillwiggins** [comment]
Problem now fixed.
