### ISSUE TITLE
Questions/ideas about 2/3 things

### ISSUE THREAD

**Issue by ScanEat** [phillwiggins/flutter_parse_sdk#44]
1) I think we can't join your http://flutter-parse-sdk.slack.com/ because you have to invite us.

2) Isn't a good idea to make a post, or maybe a text in the README to inform, with a list what will be the futures features that you will implement or fixes, ranked by priority ?

3) Just to talk about ParseConfig, I think it can be a future interessant feature future ( https://docs.parseplatform.org/android/guide/#config )

**Comment by phillwiggins** [comment]
1. Should be public but if not, please send me your email address and I will invite. If you want to privately send your email to phill.wiggins@gmail.com and I will add you.

2. Good idea

3. Again, good idea. Very keen on this one. Shouldn't be too difficult to implement.

**Comment by phillwiggins** [comment]
3. Added in v1.0.10
