### ISSUE TITLE
className doesn't come right in custom query

### ISSUE THREAD

**Issue by cetorres** [phillwiggins/flutter_parse_sdk#49]
Hi,

This is how I'm doing the query. My custom class is called Customer:
var query = "order=name";
var response = await ParseObject('Customer').query(query);

This is the debug print as the result of the query. Notice that the className doesn't bring the correct name of the class, that was supposed to bring "Customer". It's bringing "className".

I/flutter (20753): Parse API Response (Customer : ParseApiRQ.query) :
I/flutter (20753): Status Code: 200
I/flutter (20753): Payload: [{"className":"className","objectId":"ok0nKdMvkI","createdAt":"2019-01-18T17:02:41.109Z","updatedAt":"2019-01-18T23:19:50.064Z","name":"Fulano de Tal","email":"fulano@tal.com","phone":"3423532","active":true,"user":null}, {"className":"className","objectId":"uT0NYuGQyM","createdAt":"2019-01-18T17:03:58.910Z","updatedAt":"2019-01-18T23:19:39.620Z","name":"José Silva","email":"jose@gmail.com","active":true,"user":null}]

**Comment by phillwiggins** [comment]
Is that you exact code for a query?

**Comment by cetorres** [comment]
Sorry, the query is working. But just the className doesn't come right as I showed in the debug print.
Also the result object inside the response brings the the class name like "classes/className".
I believe it was supposed to bring the correct name of the custom class (from my Parse server).

**Comment by cetorres** [comment]
No, there's no field called className. That's from the response result.

**Comment by phillwiggins** [comment]
Can you post your full query please?

I'm not sure how to help on this with out anything to work with.
