### ISSUE TITLE
How to perform relational queries with Pointers?

### ISSUE THREAD

**Issue by cetorres** [phillwiggins/flutter_parse_sdk#51]
I have a class Customer that has a property user. That's a Pointer to User. How can I perform a query that does this where?

where={"user":{"__type":"Pointer","className":"_User","objectId":"8TOXdXf3tz"}}

**Comment by phillwiggins** [comment]
Add .included next(ParseUser) to your search.

**Comment by cetorres** [comment]
Can you give an example, please?

**Comment by phillwiggins** [comment]
There is an example in the example app.

Main.dart

**Comment by cetorres** [comment]
I saw that one: .includeObject(['Day']). But that just includes the Pointer data into the main query. But doesn't filter by the objectId, which is what I want. 
There query is like, give me the customers from this user.

With this request I can achieve the query:

https://YOUR.PARSE-SERVER.HERE/parse/classes/Customer?where={"user":{"__type":"Pointer","className":"_User","objectId":"8TOXdXf3tz"}}

But how to do it with the QueryBuilder? Now I can only do with custom query from the ParseObject.

**Comment by phillwiggins** [comment]
Add whereEquals(objectId) to the query?

**Comment by cetorres** [comment]
No. It would be using whereEqualTo('user', user). Sending the user as a ParseUser doesn't work. I believe because Parse stores this user on Customer class as a Pointer to User. So it's a Pointer object. So the solution would be perform a subquery, as the REST API suggests, do a inQuery:

&where={"user":{"\$inQuery":{"where":{"objectId":"${user.get('objectId')}"},"className":"_User"}}}

**Comment by phillwiggins** [comment]
Can you send me the section of the REST API you are referring too. I don't
understand.

**Comment by cetorres** [comment]
https://docs.parseplatform.org/rest/guide/#relational-queries

**Comment by phillwiggins** [comment]
I see.

This feature has not been added yet. It will be in the near future.

**Comment by cetorres** [comment]
Ah ok, good to know. Thank you.

**Comment by rodrigosmarques** [comment]
@cetorres 
It's working. You can test with last release.

```
      var queryBuilder = QueryBuilder<ParseObject>(ParseObject('Product'))
        ..whereEqualTo("owner", user.toPointer());

```

**Comment by rodrigosmarques** [comment]
@phillwiggins 
this issue can be closed.

Resolved in the last release.

**Comment by cetorres** [comment]
Thank you, guys!

**Comment by rodrigosmarques** [comment]
@cetorres 
 you are Brazilian?

**Comment by cetorres** [comment]
Yes, @rodrigosmarques. You too?

**Comment by rodrigosmarques** [comment]
Me too. I live in Vitória - ES.

Nice. I speak. I know a few Brazilians who use Parse.

**Comment by rodrigosmarques** [comment]
@phillwiggins
Close this issue to keep open only what is in trouble.
Resolved in previous releases. It is inactive because it has not received any new comments.
