### ISSUE TITLE
becomeInBackground

### ISSUE THREAD

**Issue by ScanEat** [phillwiggins/flutter_parse_sdk#61]
Hi,

Is it possible to use becomeInBackground (like in the Android guide from Parse : https://docs.parseplatform.org/android/guide/#setting-the-current-user)

```
ParseUser.becomeInBackground("session-token-here", new LogInCallback() {
  public void done(ParseUser user, ParseException e) {
    if (user != null) {
      // The current user is now set to user.
    } else {
      // The token could not be validated.
    }
  }
});
```

**Comment by pcegarra** [comment]
Yes, you need to send the token from a cloud function, and then you can do this:

```
initUserFromToken () async{
    ParseUser user = new ParseUser(null,null,null);
    var response = await user.getCurrentUserFromServer(token:"r:78095e44937ff1732f18ea04d04ad67e");
    if (response.success){
      user = await ParseUser.currentUser();
      print("user"+user.get(ParseUser.keyUsername));
    }
  }
```

But this is not in release, so we need to wait to the new release, see https://github.com/phillwiggins/flutter_parse_sdk/issues/58

**Comment by ScanEat** [comment]
Oh ok and could you show me an exemple of how you retrieve the token from your cloud function response please ?

**Comment by pcegarra** [comment]
Yes, this is not a cloud function, but you can do something like this, and return the token in the cloud function.

    async function getTokenFromUser(user: Parse.User): Promise<string> {
        var randomPassword = generateRandomPw();
        user.setPassword(randomPassword);
        await user.save(null, {useMasterKey: true});
        user = await Parse.User.logIn(user.get("username"), "" + randomPassword);
        return user.getSessionToken();
    }

I dont know if this code will work for you, Im doing a login without password, its by email link/code.

**Comment by ScanEat** [comment]
Oh, I can't call .getSessionToken() on my user, where this method comes from ?

**Comment by pcegarra** [comment]
Is a js method, in your cloud code you can call it:
https://parseplatform.org/Parse-SDK-JS/api/2.1.0/Parse.Session.html#getSessionToken

**Comment by ScanEat** [comment]
Oh ok and is it possible to retrieve this token in app with Dart code ?

**Comment by pcegarra** [comment]
Why do you need login with token?

**Comment by ScanEat** [comment]
Because it's the way that I have to login on my server like this : https://docs.parseplatform.org/android/guide/#setting-the-current-user

**Comment by pcegarra** [comment]
You can do the normal way:
https://docs.parseplatform.org/android/guide/#logging-in

This is implemented in this sdk, with username and password
