### ISSUE TITLE
currentUser doesn't get updated even after calling getUserFromServer

### ISSUE THREAD

**Issue by eslamira** [phillwiggins/flutter_parse_sdk#65]
ParseUser.currentUser(); once called the currentUser i get doesn't get updated again for example i update the user's values and save them to the database and when i cal getUserfromServer it get the values right but doesn't show in currentUser unless i completely remove the cache data like remove the app from the phone and then the updated data is in the currentUser but again it doesn't update at all

these are the log from the normal run i added some values to user saved it and it does show for the getUserFromServer but not for the local currentUser (the one with minus sign in it is the currentUser)

> 
> {"className":"_User","objectId":"UdMqp45eTs","createdAt":"2019-01-27T16:05:46.340Z","updatedAt":"2019-01-31T22:39:36.045Z","username":"+201144753259","secondarySubscription":"{\"__type\": \"Pointer\", \"className\": \"Subscription\", \"objectId\": \"xxxxxxxxxxx\"}","primarySubscription":"{\"__type\": \"Pointer\", \"className\": \"Subscription\", \"objectId\": \"fffffffff\"}","services":null,"ACL":{"*":{"read":true},"UdMqp45eTs":{"read":true,"write":true}},"sessionToken":"r:46a7f17dd2aa364909530241a7bc5c94"}
> --------------{"className":"_User","objectId":"UdMqp45eTs","createdAt":"2019-01-27T16:05:46.340Z","updatedAt":"2019-01-31T22:39:36.045Z","username":"+201144753259","password":"+201144753259","services":null,"ACL":{"*":{"read":true},"UdMqp45eTs":{"read":true,"write":true}},"sessionToken":"r:46a7f17dd2aa364909530241a7bc5c94"}

and these are the logs after removing the cache => now i'm getting it right

> 
>{"className":"_User","objectId":"UdMqp45eTs","createdAt":"2019-01-27T16:05:46.340Z","updatedAt":"2019-01-31T22:39:36.045Z","username":"+201144753259","secondarySubscription":"{\"__type\": \"Pointer\", \"className\": \"Subscription\", \"objectId\": \"xxxxxxxxxxx\"}","primarySubscription":"{\"__type\": \"Pointer\", \"className\": \"Subscription\", \"objectId\": \"fffffffff\"}","services":null,"ACL":{"*":{"read":true},"UdMqp45eTs":{"read":true,"write":true}},"sessionToken":"r:46a7f17dd2aa364909530241a7bc5c94"}
> --------------{"className":"_User","objectId":"UdMqp45eTs","createdAt":"2019-01-27T16:05:46.340Z","updatedAt":"2019-01-31T22:39:36.045Z","username":"+201144753259","password":"+201144753259","secondarySubscription":"{\"__type\": \"Pointer\", \"className\": \"Subscription\", \"objectId\": \"xxxxxxxxxxx\"}","primarySubscription":"{\"__type\": \"Pointer\", \"className\": \"Subscription\", \"objectId\": \"fffffffff\"}","services":null,"ACL":{"*":{"read":true},"UdMqp45eTs":{"read":true,"write":true}},"sessionToken":"r:46a7f17dd2aa364909530241a7bc5c94"}
> 

so is that normal ??
also i think this is related to the logout issue i previously issued

**Comment by phillwiggins** [comment]
Oh I get you... The current user isn't locally being updated, even if the
server is? Is that correct?

**Comment by phillwiggins** [comment]
Okay thanks for the heads up. I'm still trying to figure out why we can't
delete local cache, not sure if it's the shared_preferences library or me.

I'll update this shortly.

**Comment by phillwiggins** [comment]
Fixed in v1.0.12
