### ISSUE TITLE
ACL - Access Control Lists

### ISSUE THREAD

**Issue by rodrigosmarques** [phillwiggins/flutter_parse_sdk#69]
Do you have plans to implement ACL?

**Comment by phillwiggins** [comment]
Hey

The plans are to have ACL suppport, but I think it's a little further down the line on the development from myself.

More than happy for you to have a go and create a PR?

**Comment by rodrigosmarques** [comment]
Hello, it's also an advanced development for me, but I'm interested in learning and developing ACL and Installation.

In the coming days, I intend to start studying a solution

**Comment by phillwiggins** [comment]
Amazing. That would be great!

Thank you, and do not hesitate to give me a shout of your getting stuck.
