### ISSUE TITLE
Save Data with Pointer

### ISSUE THREAD

**Issue by rodrigosmarques** [phillwiggins/flutter_parse_sdk#87]
Is it possible to save data in a class with Pointer (relational data)?

**Comment by rodrigosmarques** [comment]
I'm working on it.

**Comment by pcegarra** [comment]
Do you need help?

**Comment by rodrigosmarques** [comment]
> Do you need help?

The current version does not allow saving data with Pointer.

I'm already working on solution for this functionality. I hope to launch in the next few days.
