### ISSUE TITLE
Increment field Example

### ISSUE THREAD

**Issue by aminediab** [phillwiggins/flutter_parse_sdk#92]
hi all!
I am trying to test the increment option using the following code but have no luck, could anyone please indicate what I am doing wrong!
Thanks,
---------------------------------------------------
var apiResponse = await DietPlan()
        .getObject('i1FgSlj5TJ');

    if (apiResponse.success && apiResponse.result != null) {
      var dietPlan = apiResponse.result as DietPlan;
      dietPlan.increment('Carbs', 10);
      dietPlan.save();
    }
----------------------------------------------------

**Comment by phillwiggins** [comment]
Hey

I think increment should increment it server side, not locally. Possibly
remove the .save line. Call increment and check the server. You could be
overwritting the incremented value... Although I could be wrong?

**Comment by aminediab** [comment]
Hi Phill, 
I tried it without the save option, still not updating the field, i am on back4app and able to verify it! no change. I understood that the increment marks the field for update, and running the save command commits the update! any thoughts, and by the way I thank you for your great efforts and support :)

**Comment by phillwiggins** [comment]
It should just work server side when you increment. The increment method returns a Result object. Can you verify the result that is returned after calling increment? 

I.e. 

'var response = dietPlan.increment('Carbs', 10);'

**Comment by aminediab** [comment]
OK the response is => (Instance of 'Future<ParseResponse>') with no returned object!
in debugging the variable it is shows a bunch of errors!

**Comment by phillwiggins** [comment]
Just to check, I must have missed out the await as it's an instance of a
Future.

My bad!

**Comment by aminediab** [comment]
Phill I don't see that you missed the await!

/// Increases a num of an object by x amount
  Future<ParseResponse> increment(String key, num amount) async {
    if (key != null) {
      return await _increment(ParseApiRQ.increment, "Increment", key, amount);
    } else {
      return null;
    }
  }

**Comment by phillwiggins** [comment]
Apologies, I meant my code example to you. I missed the await.

'var response = await dietPlan.increment('Carbs', 10);'

**Comment by aminediab** [comment]
OK, now the response result is null, and i have a parse error: Unexpected End of Json Input

**Comment by phillwiggins** [comment]
Ah okay so it looks to be an error with the SDK. I'll look into that
tomorrow for you!

**Comment by aminediab** [comment]
Great, I have another question when deleting and object the two parameters are path and objectId. The path is the local storage path, when pinning an object, lets say i want to pin a diet plan object, what path do i use for deleting it in both online and local?

**Comment by aminediab** [comment]
I did not realize it was that late in the evening! good night we'll pick it up tomorrow, thanks a lot

**Comment by phillwiggins** [comment]
Hey, yeah that is an issue. I noticed it the other day. It's been changed
by a contributor that was looking to delete ParseFiles. That will be fixed
shortly.

**Comment by aminediab** [comment]
Good Morning Phill,
Thank you for taking the time to fix the errors. I have another question, after successfully pinning a diet_plan object I tried to delete it online and locally, however I don't know what is the path that i should use, in this case used null! I can delete online but not locally, to test I used the following code as example, what is the path syntax?

void deleteDietPlanObject() async {
    var apiResponse = await DietPlan().delete(null, 'i1FgSlj5TJ');
    if (apiResponse.success && apiResponse.result != null) {
      print(ApplicationConstants.keyAppName +
          ": " +
          apiResponse.result.toString());
    }

// test if pin exists    
DietPlan newDietPlanFromPin = await DietPlan().fromPin('i1FgSlj5TJ');
    if (newDietPlanFromPin != null) {
      print(newDietPlanFromPin.get('Carbs'));
      print('Retreiving from pin worked!');
    } else {
      print('Error');
    }
  }

**Comment by phillwiggins** [comment]
That will be removed shortly. It should be an optional for path, not a
requirement.

I'll amend that in the next release.

**Comment by rodrigosmarques** [comment]
@phillwiggins and @aminediab.

I found the reason for the error in increment and decrement. I'm completing the tests and I'm going to upload a PR.

The same solution will solve problems in addAll, addUnique and add in List.

I'll also add support for Pointer.

Same as increment and decrement and list operations, saving a Pointer must be done in two steps at creation.

First you must save the object and then use the result of the Response (as ParseObject) and perform the operations.

During creation ParseObject does not have the objectId, only the response it has. Then the response is used to perform the operations.

Sorry, I'm not fluent in English I'm using a translator for support.

**Comment by phillwiggins** [comment]
Great work Rodrigo!

I've not had a chance to use this feature in my own apps yet so I didn't
realise they weren't working correctly. I'll review the code as soon as you
create a PR. Again, thank you!

**Comment by aminediab** [comment]
Thanks Rodrigo!

**Comment by aminediab** [comment]
Phill/Rodrigo,

You all are doing a Great Job. I really believe, once most of the parse server functionality is implemented and tested, this Flutter Parse Server Package will surely be in the Top 10!

As a reminder, The increment and decrement still not working as of your latest git. Rodrigo mentioned he is going to fix it!

**Comment by rodrigosmarques** [comment]
Hi @aminediab,
I had changed and tested counters (increment and decrement).
I checked now that the changes did not go up to git. I am checking what happened and I will soon do a PR.

**Comment by rodrigosmarques** [comment]
Hi @aminediab.
Try again.

Update **pubspec.yaml**

-----

dependencies:
  flutter:
    sdk: flutter
  #parse_server_sdk: ^1.0.15
  parse_server_sdk: 
     git: git://github.com/phillwiggins/flutter_parse_sdk.git

-----

**Comment by aminediab** [comment]
Hi Rodrigo,
I updated pubspec.yaml, the apiResponse.result returns the object successfuly. However, it failed on increment with error, parse error ! I also tried it with saving and without saving(last statement), 

void incrementDietPlanProtein() async {
    var apiResponse = await DietPlan().getObject('mqinMzhxJY');

    if (apiResponse.success && apiResponse.result != null) {
      var myDiet = (apiResponse.result as DietPlan);
      var response = await myDiet.increment('Protein', 10);
      //myDiet.save();
    }
  }

**Comment by rodrigosmarques** [comment]
Hi @aminediab 

You can verify that the file code "lib/src/objects/parse_object.dart" in your local repository contains these changes here: https://github.com/phillwiggins/flutter_parse_sdk/pull/107/files

You can check this using Go To -> Declaration in Android Studio or Go To Definition in Visual Code

If you wait a while, I've created the setIncrement and setDecrement methods to be used in conjunction with save (), same as library for Android / iOS.

For example:
`
    var parseObject = ParseObject ("TestAPI", debug: true);
    parseObject.setIncrement ("intNumber2", 2);
   parseObject.setDecrement ("intNumber3", 2);
   apiResponse = await parseObject.save ();
`
I am finalizing the tests and I must release today or tomorrow.

**Comment by rodrigosmarques** [comment]
Hi @aminediab 

Did you take the test again? The new features are available in the latest release.

**Comment by rodrigosmarques** [comment]
@phillwiggins 
this issue can be closed.

Resolved in the last release.

**Comment by rodrigosmarques** [comment]
@phillwiggins
Close this issue to keep open only what is in trouble.
Resolved in previous releases. It is inactive because it has not received any new comments.
