### ISSUE TITLE
Problem with parseEncode function in version 1.0.14

### ISSUE THREAD

**Issue by rodrigosmarques** [phillwiggins/flutter_parse_sdk#99]
After update to version 1.0.14 I have problem with parseEncode function.

The function abort execution with message ""Failed assertion: boolean expression must not be null""

![captura de tela 2019-03-07 as 00 41 00](https://user-images.githubusercontent.com/17687286/53930875-c6a9a700-4071-11e9-947b-953d35223c7a.png)

The problem occurs in Login, apiResponse.result from Query and others cases.

I try return to version 1.0.13, same with parse_server_sdk: ^1.0.13 in pubspec.yaml, the install version is 1.0.14

**Comment by phillwiggins** [comment]
I see.

Looks like a merge issue has happened. I'll fix this right away.

**Comment by rodrigosmarques** [comment]
Hello, Phill, I ran the sample code and it also presented the same error.

You're very quick on the answers.

**Comment by phillwiggins** [comment]
Just taken a look at this issues.

Seems very confusing, but I think small fix might do. As you can see, there
is a default bool set as false. I'll try correct that if null instead. I'll
do a hotfix now

**Comment by phillwiggins** [comment]
1.0.15 is now released.

I couldn't replicate the issue you were having but hopefully this now works. Please let me know if it persists.

**Comment by rodrigosmarques** [comment]
OK Phill, I'll test and if I complete the tests, I'll send a Pull Request with changes to add and remove a Pointer. this lib is getting full. Congratulations on your initiative.

**Comment by rodrigosmarques** [comment]
Resolved. Thanks.
